travis:
  secure:
    BINSTAR_TOKEN: PVFKR/iZ/qAQDexEG7CHf8Ixs14V9mRKq+GewVvLd2I7PbF2UI9q7TfKHW+9Dioi6Cmxwq+BV7s8zhkYlr5m+lvCsthcMYD0JRs3B/4oNZPrSesp1jA+cVH5Jw83IfhLsvy1nmmWxIH9xl4tLZGN4CxkBDwFlZVC/AUGeaE9XxI9jV/tMuoP4Ui2W8SjUuM7UbNU9g/VwAbLATE1FYzKRb4QXiQzWDf1lR+VMa43j0CYpsGVw8DVf6JTNwn0dLl2ZN1Ri35grtnuGx2JXRLA0UJsS8onWK6pKQQ6xoIFBC4WssYkbLlnb6JTaYPfsBGq8RhlzN2oxDZGMKVoeAqiMXSWXsynQGJD2/BGwyB/nJ9uT89IwSd0sBlORF8RQo9TueCckLpZdVZZacmgIlKhSuNc5N4ZxTBobeHRNA5LLs7ZSTRFlFCOni50XdL2DVWLAN0ySMckXF/3EaoVrvgh3EC7fh4CGwTdA9Z2IrcX9+PFSNRAtWTub6EQZMHnR4MzmTrLd3ny2rYH6j5H5lgtqsLHRgpaw0r4f7eW8s1IaB6BpkWOgoaqqmdFnLuxVYKK0qTiecks2ltx+cdiyMlbxwNwjfc3ykdtTYw37jqMagwjoD86BzBhU0aCjuiXeGN6RCap7G00TBvdxpo0nKPZT+NiU2xqkQCDE6QjO4u3mHk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
