travis:
  secure:
    BINSTAR_TOKEN: EE9/+Hfw74WKWYeExFaY1RPFMZ/tIRiC/P8fR0SzFf/TJktE+2VUf55J/zSvVn5Sg5Gsj3BFH8ylPQlYYb+TjSQtgCqCnljACpGRxOaTfq+/c3yMJvMESJwB5BRmtg6/oBP+rM8jEPulUZdl9Dne6qeadGVbwxZh0JV/EoApIAgwrWy0hKv2Bsg+d0T33ldpSvVJAWKUTI2Vn5TsBGiy+nsaacUUfFO1mg9fL443F76nrTWGoSA/pw5d203uD01Wa+2uHnPA5yJ1HXM4EdXVGzUzGxibtFWEapSKHPwDtce0X3FIM/J+oc0pC6hFWOxpQPH5Nu9rboW89g87RzZ3IF3TWI+kRi4A6LowX8auq8jtmbAdqnSiQSh0JLLzKMV4BQ12ce4tQjZqCcHZzvmWmj+fhUwkf5Kz9FCpHFMx171p2jOKBKscWXyZ1FUO45YkczBLvHNRV4a+MiFwvWye3o2DtXUH10AI6oe3Lu59cT1wCQKajvM4KVRtJbuvjj5stuKvn+XYt1TpJR30ILW8HbJZaLzYDrxhsfDaRZkG7L2K5dwCIV2fJWEdsg0GqpWZqEVVo3gu44bQqsJagbHhs6AgApOZzK2640avQfcM9MIU1xcZ8c8+50XT4WxfIvUeu7GUn0YdWcOt/nucM7sMinfyP/B9BhBSQV5Gu6WWzpE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
